package com.lukkien.controller;
import com.lukkien.dto.AirportsDto;
import com.lukkien.dto.FlightResultsDto;
import com.lukkien.model.Airport;
import com.lukkien.service.FlightService;
import com.lukkien.service.impl.FlightServiceImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//@Controller
@RestController
public class FlightSearchController {

    @Autowired
    FlightService flightServiceImpl;

    private static final Logger logger = LogManager.getLogger(FlightSearchController.class);


    private final AtomicLong counter = new AtomicLong();
    private static final String template = "Hello, %s!";

    //Website
    //Statics
    //Spring restful-- completed
    //Spring boot -- completed
    @RequestMapping(value ="/getResults" , method = RequestMethod.GET)
    public @ResponseBody
    List<FlightResultsDto> getResults(@RequestParam("departure")
                                                 Airport departure, @RequestParam("arrival")
            Airport arrival) {
        logger.info("info flight search executed");
        List<FlightResultsDto> flightsResults = flightServiceImpl.findFlights(departure, arrival);
        return flightsResults;
    }

    @RequestMapping(value ="/getAirportNames" , method = {RequestMethod.GET, RequestMethod.POST})
    public @ResponseBody
    AirportsDto getAirportNames(@RequestParam(name="airportName", required=true) String airportName) {
        logger.info("info getAirportNames executed");
        String a[] = new String[]{"abc","klm","xyz","pqr"};
        //List <String> airportNames = Arrays.asList(a);
        AirportsDto an = new AirportsDto();
        //an.setAirportNames(airportNames);
        return an;
    }

}